namespace: airflow

stack:
  defines: process-group
  runnable-list:
    - airflow/airflow-redis
    - airflow/airflow-db
    - airflow/airflow-webserver
    - airflow/airflow-scheduler
    - airflow/airflow-worker
    - airflow/airflow-triggerer
    - airflow/airflow-init
  variables:
    database_name:
      type: string
      value: airflow
    database_password:
      type: string
      value: airflow
    database_user:
      type: string
      value: airflow
    database_port:
      type: int
      value: 5432
    airflow_username:
      type: string
      value: airflow
    airflow_password:
      type: string
      value: airflow
    webserver_port:
      type: int
      value: 8080